[package]
name = "os_boot"
version = "0.1.0"
authors = ["ishanjain28 <ishanjain28@gmail.com>"]

[dependencies]
volatile = "0.2.3"
spin = "0.4.6"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[package.metadata.bootimage]
default-target = "x86_64-os.json"
